sudo: required         # need super-user permission
services:
        - docker       # installs a docker copy   
before_install:        # build docker image from file with tag
        - docker build -t gkulkarni05/docker-react -f Dockerfile.dev .
script:                # run test with no manual commands/intervention
        - docker run gkulkarni05/docker-react npm run test -- --coverage
deploy:
        provider: elasticbeanstalk
        region: "us-east-2" 
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-2-035962872218"
        bucket_path: "docker-react"
        on: 
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"

     
   
